os:
  - linux
  - osx

osx_image: xcode10.3
sudo: true
dist: trusty
language: node_js
node_js:
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - ./.travis/script.sh

branches:
  only:
    - master