osx_image: xcode7.3

sudo: required
dist: trusty

language: c

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

install:
- nvm install 6
- npm install
- npm prune

script:
- npm run dist-mac

branches:
  only:
    - master